# Generated by Django 3.1.3 on 2021-04-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
